import { EvidenceArtifact, EvidenceType } from "@/types/evidence"

export function generateMockArtifact(
  name: string,
  type: EvidenceType,
  endpointHostname: string,
  endpointId: string,
  investigationId: string = "inv-2026-001"
): EvidenceArtifact {
  const randomHex = () =>
    Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join("")

  const hash = randomHex()
  const chainHash = randomHex()

  return {
    id: `art-${Date.now().toString(36)}`,
    investigationId,
    endpointId,
    endpointHostname,
    name,
    type,
    evidenceClass: "PROCESS",
    executionProfileId: "PROFILE-A",
    executionProfileName: "VOLATILE TRIAGE",
    collector: "nexus-agent-v1",
    sizeBytes: Math.floor(Math.random() * 50_000_000) + 1024,
    sha256: hash,
    collectedAt: new Date().toISOString(),
    sourcePath: `C:\\Forensics\\Simulated\\${name}`,
    chainHash,
    merkleLeafIndex: Math.floor(Math.random() * 100) + 1,
    integrityVerified: true,
    integrityStatus: "VERIFIED",
    provenanceStatus: "SEALED",
    normalizedType: type,
    schemaStatus: "NORMALIZED",
    tags: ["Simulated", "AutoGenerated", type],
    metadata: {
      generatedBy: "Nexus-Prototype-Evidence-Generator",
      verified: true,
    },
    custodyChain: [
      {
        timestamp: new Date().toISOString(),
        action: "COLLECTED",
        operator: `agent:${endpointId}`,
        nodeId: endpointId,
        signature: `SIG-${randomHex().slice(0, 32)}`,
      },
    ],
  }
}
